[rocm-libraries] ROCm/rocm-libraries#2021 (commit 6aee89d)
[rocsparse] Fix building rocsparse with install script on
 centos9 (#2021)

## Motivation

Fix building rocsparse with install script on centos9

## Technical Details

Fix failures in getting python and pyyaml dependencies on centos stream
9:

Installing python36 from distro package manager
Last metadata expiration check: 0:14:40 ago on Wed 08 Oct 2025 06:18:11
PM UTC.
No match for argument: python36
Error: Unable to find a match: python36

## Test Plan

Ensure all CI tests pass