[rocsparse] Fix std::fma casting in host routines to properly deduce types (#1940)
## Motivation

Fixes errors that were occurring on some machines related to deducing
the correct type to use with `std::fma`

## Technical Details

Was getting compilation errors like: `error: call to '__test' is
ambiguous` because the correct type passed to `std::fma` could not be
properly deduced. This was occurring in host functions like host_axpby
where we were using std::fma with the mixed types `rocsparse_bfloat16`
and `float` for the parameters. Solution is to always static cast to the
compute type T in these functions (which will be `float`, `double` or
their complex equivalents).

## Test Plan

Verify all CI tests pass